# Generated by Django 5.1.4 on 2024-12-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STIWEBSERVICE', '0009_delete_tecnico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
            ],
        ),
    ]
