# Generated by Django 5.1.4 on 2024-12-14 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STIWEBSERVICE', '0010_tecnico'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tecnico',
        ),
    ]
